//Downloads
resource.AddWorkshop("182104437")
resource.AddWorkshop("132835998")

//Random Box
resource.AddFile( "models/toybox.mdl" )
resource.AddFile( "materials/models/toybox/zombie_treasure_box_c.vmt" )
resource.AddFile( "materials/models/toybox/zombie_treasure_box_c.vtf" )
resource.AddFile( "materials/models/toybox/zombie_treasure_fill_c.vmt" )
resource.AddFile( "materials/models/toybox/zombie_treasure_fill_c.vtf" )
resource.AddFile( "materials/models/toybox/zombie_treasure_fill_c.vtf" )
	
//Fonts
resource.AddFile( "resource/fonts/BOYCOTT_.ttf" )
	
//Perkacola & PP
resource.AddFile( "models/perkacola/dtap.mdl" )
resource.AddFile( "models/perkacola/jug.mdl" )
resource.AddFile( "models/perkacola/packapunch.mdl" )
resource.AddFile( "models/perkacola/revive.mdl" )
resource.AddFile( "models/perkacola/sleight.mdl" )
resource.AddFile( "materials/models/perkacola/pack_a_punch_c.vmt" )
resource.AddFile( "materials/models/perkacola/pack_a_punch_c.vtf" )
resource.AddFile( "materials/models/perkacola/pack_a_punch_moving_c.vmt" )
resource.AddFile( "materials/models/perkacola/pack_a_punch_moving_c.vtf" )
resource.AddFile( "materials/models/perkacola/pack_a_punch_moving_n.vtf" )
resource.AddFile( "materials/models/perkacola/pack_a_punch_n.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_perkbottle_jugg_n.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_perkbottle_sleight_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_perkbottle_sleight_c.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_doubletap_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_doubletap_c.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_doubletap_n.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_jugg_col.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_jugg_col.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_jugg_norm.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_revive_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_revive_c.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_revive_n.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_revsign_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_revsign_c.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_revsign_n.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_c.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_gc.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_gc.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_logo_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_logo_c.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_sleight_n.vtf" )
resource.AddFile( "materials/models/perkacola/zombie_vending_vent_power_on_c.vmt" )
resource.AddFile( "materials/models/perkacola/zombie_vending_vent_power_on_c.vtf" )